### ISSUE TITLE
1 packages failed. 

### ISSUE THREAD

**Issue by keyohan** [thien94/orb_slam3_ros#2]
May i ask why "1 package failed" in the "catkin build"step?

**Comment by thien94** [comment]
Hi @keyohan , that means some errors occurred and the build step has failed. Could you take a look at the terminal output and check what is the error message?

**Comment by keyohan** [comment]
> 你好 @keyohan，这意味着发生了一些错误并且构建步骤失败。 您能否查看终端输出并检查错误消息是什么？

Its Ok, this error is mainly due to the opencv version. I just changed the version in cmakelists.

**Comment by nypyp** [comment]
> 

hi, I have changed the version in the cmakelist, but still get build failed, could you tell me the the version of your opencv, pangolin and eigen?
