### ISSUE TITLE
ROS2 port?

### ISSUE THREAD

**Issue by Mechazo11** [thien94/orb_slam3_ros#25]
Hi @thien94,

Thank you very much for your great work. Its been a core part of my research in VSLAM systems.

I am attempting to modify your code to move the project into ROS2. At the moment I am unable to get the project to compile. The project structure, current cmake and the error that I am getting are shown in this question https://robotics.stackexchange.com/questions/105973/stuck-with-cmake-configuration-for-a-ros2-cpp-node-that-builds-a-library-within

Would you kindly help?

With best
@Mechazo11

**Comment by thien94** [comment]
Hi @Mechazo11 , thank you kindly for testing out the project. I can see in the linked forum post that you have found a solution to the problem. Is that the case or do you still face some other challenges?

**Comment by Mechazo11** [comment]
@thien94 Yes, apart from the dynamic library issues, there were a few others but I have solved them all and have successfully created a ROS2 version of your ROS1 port of ORB SLAM3 V1.0. Here is the link to the repository: https://github.com/Mechazo11/ros2_orb_slam3/tree/main. 

Have you noticed that the copy of ORB SLAM3 V1.0 that is present in this repository is still using a old version of g2o? I tried a day or two to get the new version working but somethings were beyond my skill at this time. Would you be interested in upgrading g2o in your ROS1 port to the latest version? I am very much interested to help in that regard.
