### ISSUE TITLE
Orb slam 3 + orb slam wrapper on an RGBD ros bag shows no cloud points

### ISSUE THREAD

**Issue by zarathacia** [thien94/orb_slam3_ros#7]
There are no errors in the run just the absence of the cloud points in RVIZ as shown in this screenshot https://imgur.com/a/ORlmEzf
I built orb slam with opencv 4.4 with installation option cuda off and no GTK 
anyone had this issue before?

**Comment by thien94** [comment]
- First, you can enable the pangolin window to check if point cloud data is available.
- If it is, you can run `rostopic hz /<name of pointcloud topic>` to verify the node is publishing data
- If the topic is being published, check that the name of the frames are correct (world_frame_id etc.)

Hope this helps.

**Comment by zarathacia** [comment]
Sorry for the delay. The node is indeed publishing data. i checked the name of the frames too. all looks good but the result is still like this https://imgur.com/OqiYCzK

**Comment by kinda-raffy** [comment]
@zarathacia If you are using the rosbag, make sure to change `RGB.DepthMapFactor` to `1.0` in `TUM<version>.yaml`. Although the points are shown correctly after this change, they seem to be all inverted on the XZ axis. @thien94 can you take a look at the following pictures?

Normal view in rviz:
![image](https://github.com/thien94/orb_slam3_ros/assets/81792786/348707d9-bfd2-41fa-82e3-afa1fd5c2b8d)

Inverted view in rviz:
![image](https://github.com/thien94/orb_slam3_ros/assets/81792786/65a4518f-6a1b-4272-b06c-f8a8cff1074b)

In the normal view, the camera frame is pointed up, with all the points being projected upwards. The camera and the points seem to be in the correct orientation if you invert the view in rviz (the inverted picture shows the camera frame pointed down). 

---

I used `roslaunch orb_slam3_ros tum_rgbd.launch` and `rosbag play rgbd_dataset_freiburg1_xyz.bag`. 

Here is my `tum_rgbd.launch`:
[tum_rgbd.launch.txt](https://github.com/thien94/orb_slam3_ros/files/11469991/tum_rgbd.launch.txt)

and my terminal output that was running roslaunch:
[orb_slam3_output.txt](https://github.com/thien94/orb_slam3_ros/files/11470000/orb_slam3_output.txt)

**Comment by zarathacia** [comment]
@shyam-botsync I didn't make other changes apart from changing values in the yaml file
